volumes:
  supallm_data:
  supallm_redis_data:
  shared_init:

networks:
  supallm-network:
    driver: bridge

services:
  supallm_setup:
    image: ghcr.io/supallm/supallm:latest
    container_name: supallm-setup
    volumes:
      - shared_init:/shared_init
    entrypoint: >
      sh -c "cp /app/db/init.sql /shared_init/init.sql"
    restart: "no"

  supallm_frontend:
    image: "ghcr.io/supallm/supallm:latest"
    container_name: supallm-frontend
    hostname: supallm-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      - supallm_api
    networks:
      - supallm-network
    environment:
      - MODE=frontend
      - PUBLIC_SUPALLM_API_URL=${SUPALLM_API_URL}

  supallm_postgres:
    image: postgres:16
    container_name: supallm-pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      supallm_setup:
        condition: service_completed_successfully
    volumes:
      - supallm_data:/var/lib/postgresql/data
      - shared_init:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - supallm-network
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "maintenance_work_mem=1GB"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  supallm_redis:
    image: redis:7.4
    container_name: supallm-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - supallm-network
    volumes:
      - supallm_redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 1GB --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  supallm_api:
    image: "ghcr.io/supallm/supallm:latest"
    container_name: supallm-api
    ports:
      - "${BACKEND_PORT:-3001}:80"
    environment:
      MODE: api
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SECRET_KEY: ${SECRET_KEY}
      INITIAL_USER_EMAIL: ${INITIAL_USER_EMAIL}
      INITIAL_USER_PASSWORD: ${INITIAL_USER_PASSWORD}
      INITIAL_USER_NAME: ${INITIAL_USER_NAME}
    depends_on:
      supallm_postgres:
        condition: service_healthy
      supallm_redis:
        condition: service_healthy
    networks:
      - supallm-network

  supallm_runner:
    image: "ghcr.io/supallm/supallm:latest"
    container_name: supallm-runner
    env_file:
      - .env
    environment:
      - MODE=runner
      - RUNNER_MAX_CONCURRENT_JOBS=5
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - supallm-network
    depends_on:
      supallm_redis:
        condition: service_healthy
