FROM golang:1.24-bullseye AS generator

RUN apt-get update && apt-get install -y git && \
    go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest

WORKDIR /utils
COPY ./openapi .

FROM generator AS generator-oapi
RUN ./genoapi.sh

FROM scratch AS oapi
COPY --from=generator-oapi /utils/gen ./gen

# #
# Frontend Generator
# #
FROM node:20-alpine AS generator-frontend
WORKDIR /utils
COPY ./openapi/ .

FROM generator-frontend AS generator-oapi-frontend
WORKDIR /utils/gen-client
RUN sh ./gen-client.sh

FROM scratch AS oapi-frontend
COPY --from=generator-oapi-frontend /utils/gen-client/src .

