openapi: 3.0.0

info:
  title: SupALLM API
  version: "0.0.1"

# Apply security globally
security:
  - BearerAuth: []

paths:
  /projects:
    get:
      summary: List all projects
      operationId: listProjects
      responses:
        "200":
          description: List of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Project"
    post:
      summary: "Create a project"
      operationId: createProject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProjectRequest"
      responses:
        "201":
          description: "Project created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"

  /projects/{projectId}:
    get:
      summary: "Get a project by ID"
      operationId: getProject
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: "Project details"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
        "404":
          description: "Project not found"
    put:
      summary: "Update a project"
      operationId: updateProject
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProjectRequest"
      responses:
        "200":
          description: "Project updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
        "404":
          description: "Project not found"
    delete:
      summary: "Delete a project"
      operationId: deleteProject
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: "Project deleted"
        "404":
          description: "Project not found"

  /projects/{projectId}/providers:
    get:
      summary: List all providers for a project
      operationId: listProviders
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: List of providers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Provider"
        "404":
          description: Project not found
    post:
      summary: "Create a provider for a project"
      operationId: createProvider
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProviderRequest"
      responses:
        "201":
          description: "Provider created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Provider"
        "400":
          description: Bad request
        "404":
          description: Project not found

  /projects/{projectId}/providers/{providerId}:
    get:
      summary: "Get a provider by ID"
      operationId: getProvider
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: providerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: "Provider details"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Provider"
        "404":
          description: Provider or project not found
    put:
      summary: "Update a provider"
      operationId: updateProvider
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: providerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProviderRequest"
      responses:
        "200":
          description: "Provider updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Provider"
        "400":
          description: Bad request
        "404":
          description: Provider or project not found
    delete:
      summary: "Delete a provider"
      operationId: deleteProvider
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: providerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: "Provider deleted"
        "404":
          description: Provider or project not found

  /projects/{projectId}/models:
    get:
      summary: List all models for a project
      operationId: listModels
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: List of models
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Model"
        "404":
          description: Project not found
    post:
      summary: "Create a model for a project"
      operationId: createModel
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateModelRequest"
      responses:
        "201":
          description: "Model created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Model"
        "400":
          description: Bad request
        "404":
          description: Project not found

  /projects/{projectId}/models/{slug}:
    get:
      summary: "Get a model by slug"
      operationId: getModel
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: slug
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Model details"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Model"
        "404":
          description: Model or project not found
    put:
      summary: "Update a model"
      operationId: updateModel
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: slug
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateModelRequest"
      responses:
        "200":
          description: "Model updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Model"
        "400":
          description: Bad request
        "404":
          description: Model or project not found
    delete:
      summary: "Delete a model"
      operationId: deleteModel
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: slug
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: "Model deleted"
        "404":
          description: Model or project not found

  /projects/{projectId}/auth:
    get:
      summary: "Get authentication configuration for a project"
      operationId: getAuth
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: "Authentication configuration"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Auth"
        "404":
          description: Project not found
    put:
      summary: "Update authentication for a project"
      operationId: updateAuth
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateAuthRequest"
      responses:
        "200":
          description: "Authentication updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Auth"
        "400":
          description: Bad request
        "404":
          description: Project not found

  /projects/{projectId}/generateText:
    post:
      summary: "Generate text (HTTP blocking)"
      operationId: generateText
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TextGenerationRequest"
      responses:
        "200":
          description: "Generated text"
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
        "400":
          description: Bad request
        "404":
          description: Project not found

  /projects/{projectId}/streamText:
    post:
      summary: "Generate text in streaming (SSE)"
      operationId: streamText
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TextGenerationRequest"
      responses:
        "200":
          description: "SSE stream of generated text"
          content:
            text/event-stream:
              schema:
                type: string
                example: 'data: {''text'': ''Hello world''}\n\n'
        "400":
          description: Bad request
        "404":
          description: Project not found

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Project:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        userId:
          type: string
          format: uuid
      required:
        - id
        - name
        - userId

    CreateProjectRequest:
      type: object
      properties:
        name:
          type: string
      required:
        - name

    UpdateProjectRequest:
      type: object
      properties:
        name:
          type: string
      required:
        - name

    ProviderType:
      type: string
      enum:
        - openai
        - anthropic

    LLMModel:
      type: string
      enum:
        - gpt-4o
        - gpt-4o-mini
        - claude-3-7-sonnet
        - claude-3-5-sonnet
        - claude-3-5-haiku

    Provider:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        provider:
          $ref: "#/components/schemas/ProviderType"
        apiKey:
          type: string
      required:
        - id
        - name
        - provider
        - apiKey

    CreateProviderRequest:
      type: object
      properties:
        name:
          type: string
        provider:
          $ref: "#/components/schemas/ProviderType"
        apiKey:
          type: string
      required:
        - name
        - provider
        - apiKey

    UpdateProviderRequest:
      type: object
      properties:
        name:
          type: string
        apiKey:
          type: string
      required:
        - name
        - apiKey

    Model:
      type: object
      properties:
        id:
          type: string
          format: uuid
        slug:
          type: string
        provider:
          $ref: "#/components/schemas/Provider"
        model:
          $ref: "#/components/schemas/LLMModel"
        systemPrompt:
          type: string
      required:
        - id
        - slug
        - provider
        - model

    CreateModelRequest:
      type: object
      properties:
        slug:
          type: string
        providerId:
          type: string
          format: uuid
        model:
          $ref: "#/components/schemas/LLMModel"
        systemPrompt:
          type: string
      required:
        - slug
        - providerId
        - model

    UpdateModelRequest:
      type: object
      properties:
        providerId:
          type: string
          format: uuid
        model:
          $ref: "#/components/schemas/LLMModel"
        systemPrompt:
          type: string
      required:
        - providerId
        - model

    Auth:
      type: object
      properties:
        provider:
          type: string
          enum:
            - supabase
        config:
          $ref: "#/components/schemas/SupabaseAuthConfig"
      required:
        - provider
        - config

    UpdateAuthRequest:
      type: object
      properties:
        provider:
          type: string
          enum:
            - supabase
        config:
          $ref: "#/components/schemas/SupabaseAuthConfig"
      required:
        - provider
        - config

    SupabaseAuthConfig:
      type: object
      properties:
        url:
          type: string
        key:
          type: string
      required:
        - url
        - key

    TextGenerationRequest:
      type: object
      properties:
        modelSlug:
          type: string
        prompt:
          type: string
        maxTokens:
          type: integer
          minimum: 1
          maximum: 4096
          default: 1024
        temperature:
          type: number
          minimum: 0
          maximum: 1
          default: 0.7
      required:
        - modelSlug
        - prompt
