// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: stream_chunk_queries.sql

package session

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const storeStreamChunk = `-- name: storeStreamChunk :exec
INSERT INTO stream_chunks (id, response_id, index, content, is_last)
VALUES ($1, $2, $3, $4, $5)
`

type storeStreamChunkParams struct {
	ID         uuid.UUID   `json:"id"`
	ResponseID uuid.UUID   `json:"response_id"`
	Index      int32       `json:"index"`
	Content    string      `json:"content"`
	IsLast     pgtype.Bool `json:"is_last"`
}

func (q *Queries) storeStreamChunk(ctx context.Context, arg storeStreamChunkParams) error {
	_, err := q.db.Exec(ctx, storeStreamChunk,
		arg.ID,
		arg.ResponseID,
		arg.Index,
		arg.Content,
		arg.IsLast,
	)
	return err
}
