// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package workflowevent

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type WorkflowEvent struct {
	ID         uuid.UUID          `json:"id"`
	WorkflowID uuid.UUID          `json:"workflow_id"`
	TriggerID  string             `json:"trigger_id"`
	EventType  string             `json:"event_type"`
	Data       []byte             `json:"data"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
