// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: llm_credential_queries.sql

package project

import (
	"context"

	"github.com/google/uuid"
)

const deleteLLMCredential = `-- name: deleteLLMCredential :exec
DELETE FROM llm_credentials
WHERE id = $1
`

func (q *Queries) deleteLLMCredential(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLLMCredential, id)
	return err
}

const llmCredentialsByProjectId = `-- name: llmCredentialsByProjectId :many
SELECT id, project_id, name, provider_type, api_key_encrypted, api_key_obfuscated, created_at, updated_at
FROM llm_credentials
WHERE project_id = $1
`

func (q *Queries) llmCredentialsByProjectId(ctx context.Context, projectID uuid.UUID) ([]LlmCredential, error) {
	rows, err := q.db.Query(ctx, llmCredentialsByProjectId, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmCredential
	for rows.Next() {
		var i LlmCredential
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.ProviderType,
			&i.ApiKeyEncrypted,
			&i.ApiKeyObfuscated,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storeLLMCredential = `-- name: storeLLMCredential :exec
INSERT INTO llm_credentials (id, project_id, name, provider_type, api_key_encrypted, api_key_obfuscated)
VALUES ($1, $2, $3, $4, $5, $6)
`

type storeLLMCredentialParams struct {
	ID               uuid.UUID `json:"id"`
	ProjectID        uuid.UUID `json:"project_id"`
	Name             string    `json:"name"`
	ProviderType     string    `json:"provider_type"`
	ApiKeyEncrypted  string    `json:"api_key_encrypted"`
	ApiKeyObfuscated string    `json:"api_key_obfuscated"`
}

func (q *Queries) storeLLMCredential(ctx context.Context, arg storeLLMCredentialParams) error {
	_, err := q.db.Exec(ctx, storeLLMCredential,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.ProviderType,
		arg.ApiKeyEncrypted,
		arg.ApiKeyObfuscated,
	)
	return err
}

const upsertLLMCredential = `-- name: upsertLLMCredential :exec
INSERT INTO llm_credentials (id, project_id, name, provider_type, api_key_encrypted, api_key_obfuscated)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) 
DO UPDATE SET
    name = EXCLUDED.name,
    provider_type = EXCLUDED.provider_type,
    api_key_encrypted = EXCLUDED.api_key_encrypted,
    api_key_obfuscated = EXCLUDED.api_key_obfuscated,
    updated_at = NOW()
`

type upsertLLMCredentialParams struct {
	ID               uuid.UUID `json:"id"`
	ProjectID        uuid.UUID `json:"project_id"`
	Name             string    `json:"name"`
	ProviderType     string    `json:"provider_type"`
	ApiKeyEncrypted  string    `json:"api_key_encrypted"`
	ApiKeyObfuscated string    `json:"api_key_obfuscated"`
}

func (q *Queries) upsertLLMCredential(ctx context.Context, arg upsertLLMCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertLLMCredential,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.ProviderType,
		arg.ApiKeyEncrypted,
		arg.ApiKeyObfuscated,
	)
	return err
}
