// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package project

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Credential struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	Name             string             `json:"name"`
	ProviderType     string             `json:"provider_type"`
	ApiKeyEncrypted  string             `json:"api_key_encrypted"`
	ApiKeyObfuscated string             `json:"api_key_obfuscated"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Model struct {
	ID            uuid.UUID          `json:"id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	CredentialID  uuid.UUID          `json:"credential_id"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	ProviderModel string             `json:"provider_model"`
	SystemPrompt  string             `json:"system_prompt"`
	Parameters    modelParameters    `json:"parameters"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID           uuid.UUID          `json:"id"`
	UserID       string             `json:"user_id"`
	Name         string             `json:"name"`
	AuthProvider authProvider       `json:"auth_provider"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
