// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package project

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type LlmProvider struct {
	ID           uuid.UUID          `json:"id"`
	ProjectID    uuid.UUID          `json:"project_id"`
	Name         string             `json:"name"`
	ProviderType string             `json:"provider_type"`
	ApiKey       string             `json:"api_key"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Model struct {
	ID           uuid.UUID          `json:"id"`
	ProjectID    uuid.UUID          `json:"project_id"`
	ProviderID   uuid.UUID          `json:"provider_id"`
	Slug         string             `json:"slug"`
	LlmModel     string             `json:"llm_model"`
	SystemPrompt pgtype.Text        `json:"system_prompt"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	AuthProvider authProvider       `json:"auth_provider"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
