// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package user

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
