FROM node:20-slim

WORKDIR /nsjail

RUN apt-get -y update \
    && apt-get install -y \
    bison=2:3.8.* \
    flex=2.6.* \
    g++=4:12.2.* \
    gcc=4:12.2.* \
    git=1:2.39.* \
    libprotobuf-dev=3.21.* \
    libnl-route-3-dev=3.7.* \
    make=4.3-4.1 \
    pkg-config=1.8.* \
    protobuf-compiler=3.21.*

RUN git clone -b master --single-branch https://github.com/google/nsjail.git .

RUN make

RUN ls -la

RUN cp /nsjail/nsjail /usr/local/bin/nsjail
RUN chmod +x /usr/local/bin/nsjail

WORKDIR /app

RUN apt-get install -y curl \
    && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs

RUN npm install -g nodemon

RUN npm install -g typescript

RUN npm install -g ts-node

COPY package*.json ./

RUN npm i

CMD ["npm", "run", "dev"]
