name: Build and Publish Docker Image with Semantic Release

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Authenticate to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Generate OpenAPI Client for Frontend
        run: |
          DOCKER_BUILDKIT=1 docker build -f Dockerfile.generate --target oapi-frontend --output ./frontend/src/lib/services/gen-api .

      - name: Test Docker Build (Fail Fast)
        run: |
          docker build -t ghcr.io/${{ github.repository }}:test .
        # If this step fails, the workflow stops, and no release is published.

      - name: Run Semantic Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release && echo "NEW_RELEASE=true" >> $GITHUB_ENV || echo "NEW_RELEASE=false" >> $GITHUB_ENV

      - name: Extract Semantic Version
        if: env.NEW_RELEASE == 'true'
        run: echo "VERSION=$(cat .VERSION)" >> $GITHUB_ENV

      - name: Tag and Push Docker Image
        if: env.NEW_RELEASE == 'true'
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          docker tag ghcr.io/${{ github.repository }}:test ghcr.io/${{ github.repository }}:$VERSION
          docker tag ghcr.io/${{ github.repository }}:$VERSION ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:$VERSION
          docker push ghcr.io/${{ github.repository }}:latest
